---
title: Nubia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
theme_version: 1.0.5
logo: 
description: Thoughts, Stories and Ideas
baseurl: ''
url: https://nubia-jekyll.netlify.com/
twitter: https://twitter.com/aspirethemes
facebook: https://www.facebook.com/aspirethemes
instagram: https://www.instagram.com/aspirethemes
markdown: kramdown
permalink: pretty
paginate: 11
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll/tagging
include:
- _pages
exclude:
- vendor
- Gemfile
- Gemfile.lock
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty
authors:
  colin:
    name:     Colin Matthews
    bio:      Senior Business Analyst and Intelligent Automation Enthusiast
